name: DiceRoll
main: net.lotfmc.epixauce.diceroll.DiceRoll
author: Epixauce
version: 1.2
description: Rolls a dice. D2-D100
commands:
    roll:
        description: Rolls dice.
        usage: /roll <dice type> <amount of dice> 